---

- name: Check hosted sites on server (Virtualmin, httpd)
  shell: "grep -e '^ServerName.*' /etc/httpd/conf/httpd.conf | awk '{print $2}'"
  register: running_sites

- name: Define running sites
  set_fact:
    sites: "{{ running_sites.stdout_lines }}"

- name: Configure logrotate (Virtualmin, httpd)
  template:
    src: 'logrotate_httpd_virtualmin.conf.j2'
    dest: '/etc/logrotate.d/virtualmin.conf'
    owner: root
    group: root
    mode: '644'
  notify: 'Run logrotate if there are changes in config file (httpd)'
